// This file will be auto-generated by the Supabase CLI command:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID --schema public > lib/database.types.ts
//
// Example structure (will be much more detailed):
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          // The data expected from the server
          id: string
          updated_at: string | null
          username: string | null
          avatar_url: string | null
          website: string | null
          // ... other profile fields you add (role, team_id, entry_date, etc.)
          role?: string | null
          team_id?: string | null
          entry_date?: string | null
          age?: number | null
          address?: string | null
          phone?: string | null
          actual_salary?: number | null
          gender?: string | null
          isp_focus?: string[] | null
        }
        Insert: {
          // The data expected to be passed to an insert operation
          id: string
          updated_at?: string | null
          username?: string | null
          avatar_url?: string | null
          website?: string | null
          // ...
          role?: string | null
          team_id?: string | null
          entry_date?: string | null
          age?: number | null
          address?: string | null
          phone?: string | null
          actual_salary?: number | null
          gender?: string | null
          isp_focus?: string[] | null
        }
        Update: {
          // The data expected to be passed to an update operation
          id?: string
          updated_at?: string | null
          username?: string | null
          avatar_url?: string | null
          website?: string | null
          // ...
          role?: string | null
          team_id?: string | null
          entry_date?: string | null
          age?: number | null
          address?: string | null
          phone?: string | null
          actual_salary?: number | null
          gender?: string | null
          isp_focus?: string[] | null
        }
      }
      teams: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      // ... other tables (servers, seed_emails, etc.) will follow a similar pattern
      servers: {
        Row: {
          id: string
          provider: string
          ip_address: string
          added_by_mailer_id: string | null
          team_id: string | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          /* ... */
        }
        Update: {
          /* ... */
        }
      }
      // ... and so on for seed_emails, proxies, rdps, daily_revenues
    }
    Views: {
      // ... any database views you create
    }
    Functions: {
      // ... any database functions you create
    }
  }
}

// You might want to export specific table types for convenience
export type Profile = Database["public"]["Tables"]["profiles"]["Row"]
export type Team = Database["public"]["Tables"]["teams"]["Row"]
export type Server = Database["public"]["Tables"]["servers"]["Row"]
// ... etc.
